### ISSUE TITLE
Low image quality in playlist

### ISSUE THREAD

**Issue by g-fb** [ludouzi/fooyin#120]
I'm using a pretty big image in the playlist and the quality is quite bad, even with the thumbnail size set to 500.

```
Resolution 2560x1440
Scale: 140%
Operating System: openSUSE Tumbleweed 20240523
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-1-default (64-bit)
Graphics Platform: Wayland
Graphics Processor: AMD Radeon RX 6600
```

Also why the double scaling in [scalePixmap](https://github.com/ludouzi/fooyin/blob/e6f4c14bc71957e9601ad10b2089cbd98a97a852/src/utils/utils.cpp#L164)?

![fooyin](https://github.com/ludouzi/fooyin/assets/50304471/6b49e36e-c1c7-4a8d-b189-ab561a29f5d4)

**Comment by ludouzi** [comment]
This is a scaling issue, as the device pixel ratio isn't currently being taken into account. Essentially, the image needs to be scaled by the device scale factor in addition to the size of the column, otherwise it will have a too low resolution and look pixelated (like the above).

The image is scaled twice in scalePixmap as the first scale uses a fast transformation and when I wrote it back in 2022, I read somewhere that this can improve the final image quality. I'll do some testing of this to check whether it's necessary or not.
