### ISSUE TITLE
Album with over 100 tracks ordered incorrectly

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#46]
Edge case I know, but if I create a playlist with an album with more than 100 tracks, it's ordered

01
02
03
04
05
06
07
08
09
10
100
101
102
...
109
11
110
111

**Comment by ludouzi** [comment]
The reason the track numbers are prefixed with '0' in the first place was to prevent the same issue with just 10 tracks. Doing it without having to prefix '00' instead will require a custom sorting method for strings. I'll see what I can do.

**Comment by ludouzi** [comment]
Turns out this was even easier than expected.

If https://github.com/ludouzi/fooyin/commit/6d8b551641f307fd244b3957b97944a9535410eb doesn't take effect, you can reset the library settings page (Library->Settings->Reset Page) to load the new default.

Or to do it yourself without pulling the latest changes and rebuilding, change the sort script in the library settings page to:

%albumartist% - %year% - %album% - $num(%disc%,5) - $num(%track%,5) - %title%
