### ISSUE TITLE
Feature request: Album art via image files

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#59]
On your ROADMAP you have the entry:

Album artwork features - downloading and storing in metadata

Are there any plans to have album art not embedded in metadata (which increases the size of each audio file), but just for the software to pick the album art from an image file in the same location (directory) as the audio files?

**Comment by ludouzi** [comment]
Yeah, there will also be an option to download and store in a custom location relative to the files.

In terms of reading album art, fooyin currently looks for image files in the same directory (using the first file it finds), and falls back to embedded art if it can´t find any. I'll be adding more finer control of that behaviour as well.

**Comment by LukeZBaker** [comment]
Strange, for my albums only embedded is found. For any music folder with a jpg or png, I can't find any that are showing in fooyin as album art.

**Comment by ludouzi** [comment]
Looks like I've found the cause. It was treating the file's full path as the directory (with the filename). 

In order to find the artwork, you'll need to remove and re-add any libraries. I'll see about adding options to perform a full rescan of a library, and a way to detect changes to directories as well (like adding artwork).
