### ISSUE TITLE
Double click to play a track

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#62]
On a fresh installation on Manjaro or Ubuntu, double clicking a track doesn't play it in browser view (may happen in other views).

If I go to Settings / Widgets / Directory Browser and just select Expand/Collapse/Play and click Apply, the double click to play a track then works fine. After closing fooyin and restarting, double click works fine too. So the bug only happens on a fresh installation.

**Comment by LukeZBaker** [comment]
Didn't fix the bug on a quick check.

**Comment by ludouzi** [comment]
Strange, it fixed it on my end. I'll try in a fresh install of Ubuntu.

**Comment by ludouzi** [comment]
I've just tested in a fresh Ubuntu 23.10 install. No settings changed in fooyin.

The bug is present at https://github.com/ludouzi/fooyin/commit/5a98a8da8e1a1b638c58322aa2ada11aa79dc18f. At https://github.com/ludouzi/fooyin/commit/8f3685549a0a3efb9d0efa5f68d213ae656f68fc the bug is fixed. I can reproduce/fix it by switching between the commits.

Did you check in another fresh install? The fix changed the indexes of all of the actions, so you can try resetting the Directory Browser settings page, or remove the the configuration file at ~/.config/fooyin/fooyin.conf

**Comment by LukeZBaker** [comment]
Yes, you're right, it is fixed with 8f36855. Sorry -- I may have forgotten to remove the config file.

**Comment by ludouzi** [comment]
No problem - glad to hear it's fixed.
