### ISSUE TITLE
Bug - Cannot handle pipewire server restarts

### ISSUE THREAD

**Issue by ripdog** [ludouzi/fooyin#85]
(sorry for the flood of issues, I'm enjoying trying out fooyin!)

Fooyin should be able to gracefully handle pipewire dying and being restarted. Currently, it takes either a restart of fooyin to restart playback, or a change of playback device in fooyin options.

**Comment by ludouzi** [comment]
Yeah, that's definitely something that needs addressing. I'll make it a priority.

**Comment by ludouzi** [comment]
I've just started working on this. 

Because we won't know if/when the PipeWire server will be started again, I think the most graceful way to handle it would be to pause playback. When the user tries to resume playback, we can attempt to initialise the output again and if successful - continue where we left off.
